name: Deploy To Vercel Prod

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Echo Vercel Token
        run: echo ${{ secrets }}

      - name: Vercel Login
        run: vercel login --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel --prod
